import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { MobileNav } from "@/components/mobile-nav";
import { Toaster } from "sonner";
import { BASE_URL, siteConfig } from "@/config/site";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: {
        default: siteConfig.title,
        template: `%s | Carles Smyrna Christian Church`,
    },
    description: "Generated by create next app",
    openGraph: {
        description:
            "Carles Smyrna Christian Church, Faith-filled community welcoming all. Worship, fellowship, and love unite us. Join our journey!",
        images: [],
    },
    metadataBase: new URL(BASE_URL),
    keywords: [
        "Carles Smyrna Christian Church",
        "Carles Christian Church",
        "Carles Church",
    ],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar />
                    <MobileNav />
                    <Toaster />
                    <main className="container mx-auto min-h-screen mt-20 px-4 sm:px-6 lg:px-8">
                        {children}
                    </main>
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
